### ISSUE TITLE
How to configure build path?

### ISSUE THREAD

**Issue by maxvonhippel** [dangtunguyen/IoTSan#1]
I'm trying to run the code but am having a lot of trouble with the build path.  Do you have any advice for how to correctly configure this?
Thanks,
Max

**Comment by dangtunguyen** [comment]
Hi Max,

If you're using Eclipse, you should add all libraries (jar files) in the "/lib" directory to your project and please make sure your Java version is 8.x

Hope it can help!
Thomas

**Comment by maxvonhippel** [comment]
Thanks for your help @dangtunguyen .  I added the jars from the /lib directory as well as [jpf](http://jpf.sourceforge.net/) for which I just downloaded the latest version.  Before doing this I have something like 12 or 18 errors for missing libraries.  Now I'm getting around 59 errors relating to `edu`.  I've tried adding `edu` to the class-path, and I've also tried individually adding each of the class folders within it, without any improvement.  The errors are like:

> BanderaTheme cannot be resolved to a type	Bandera.java	/IoTSan/src	line 122	Java Problem
> Driver cannot be resolved to a type	Bandera.java	/IoTSan/src	line 78	Java Problem
> edu cannot be resolved	Bandera.java	/IoTSan/src	line 215	Java Problem

... etc.  I'm sure I'm making some simple mistake and apologize for the inconvenience, but if you have the time to help diagnose / remedy this I'd really appreciate it.  Thanks!

**Comment by maxvonhippel** [comment]
This is the closest I've gotten so far.

````
mvh@mvh:~/projects/research/thesis/tools/IoTSan/src$ javac -d "../bin/" -cp "../lib/*;~/home/mvh/tools/jpf-core/build/jpf.jar" IotSan.java 
IotSan.java:1: error: package edu.ksu.cis.bandera.bui does not exist
import edu.ksu.cis.bandera.bui.GDriver;
                              ^
IotSan.java:10: error: cannot find symbol
		GDriver driver = new GDriver(false);
		^
  symbol:   class GDriver
  location: class IotSan
IotSan.java:10: error: cannot find symbol
		GDriver driver = new GDriver(false);
		                     ^
  symbol:   class GDriver
  location: class IotSan
3 errors
````

Actually, I think I may have found a seperate issue.  `jpf` does not appear to be an included library and I assumed it referred to Java Plugin Framework.  But upon further googling I think you meant Java Path-Finder.

On the other hand, if I include `.` in my classpath, or use `:` rather than `;`, I get 100+ errors:

````
// lots of stuff
                       ^
  symbol:   class Stmt
  location: class Statements
./edu/ksu/cis/bandera/annotation/Statements.java:151: error: cannot find symbol
public boolean replace(Stmt oldStmt, Stmt newStmt) {
                                     ^
  symbol:   class Stmt
  location: class Statements
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
````

Update: upon further research it looks like almost all if not all my errors right now are coming from `groovy` imports, like these:

````
import org.codehaus.groovy.ast.ClassCodeVisitorSupport;
import org.codehaus.groovy.ast.expr.ConstantExpression;
import org.codehaus.groovy.ast.expr.Expression;
import org.codehaus.groovy.ast.expr.MethodCallExpression;
import org.codehaus.groovy.ast.expr.VariableExpression;
import org.codehaus.groovy.control.SourceUnit;
````

**Comment by maxvonhippel** [comment]
Update: **finally managed to get the code to run.**  I had previously installed Spin so I'm skipping that step in this documentation.  Here is what I did:

1. I followed the instructions [here](https://github.com/collab-uniba/socialcde4eclipse/wiki/How-to-import-a-GitHub-project-into-Eclipse) up until the "**in the rest of this guide ...**" part, exclusive.
2. The github repo is already an Eclipse project so I just open it in Eclipse once cloning completes, without making a new project.  I did this in a folder I made at `home/workspace`.
3. I downloaded [jpf (= Java Path Finder) here](https://github.com/javapathfinder/jpf-core) and put it in `workspace`.  Note that the NASA open source repository [here](https://code.nasa.gov/) does **not** work (see [here](http://babelfish.arc.nasa.gov/trac/jpf/wiki/install/repositories) specifically), because of a mis-configuration of credential settings with the server.  I previously worked at NASA, and emailed my  mentor there to see if he could get in touch with someone who might be able to fix this.  Other people have already contacted NASA over public email chains to no avail.  Note that JPF is not included in the IoTSan repository, so it might be a good idea to add to `lib/` if doing so is not contrary to the license or anything.
4. I installed Groovy on my computer: `curl -s get.sdkman.io | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install groovy`
5. I downloaded the **SDK Bundle** option for Groovy [here](http://groovy-lang.org/download.html)
6. I added `groovy-3.0.0-alpha-3.jar` from the **SDK Bundle** to the Java Build Path, and used `Order and Export` to move it to the top.  I put the `Persisted Container` for Groovy right below it in the order (whatever that is, I have no clue), with `IoTSan/src` after that.
7. For each of the items in the Java Build Path which had a little error symbol next to it, I double clicked on the item, found it in `lib/`, and added it.  These are things where the `.classpath` file has `dangtanguyen/workspace/...` in the directories so you have to replace those with the absolute paths on your personal computer (in this case, on my computer).
8. Since JPF is not in the `lib/` folder, when I did step 7 on JPF this required finding the `JPF.jar` file in the downloaded JPF repository from step 3.
9. In Eclipse I did Clean, Refresh, then:
10. Project -> IotSan.java -> run as Java Application

... and it worked!

For future reference, in case anyone finds this useful, my current `.classpath` is as follows:

![javabuildpath](https://user-images.githubusercontent.com/4683443/48533134-7c04e480-e860-11e8-8a6e-a47896c9824a.png)

@dangtunguyen I think it would make sense to add `JPF` and `Groovy` to `lib/`.  I would be happy to make these changes myself in a PR, if that is OK with you and if you agree with me.  If you think that this would violate some license or be otherwise problematic, another alternative would be to have a `Makefile` that would have a `initialize` entry which, among other things, would download `JPF` and `Groovy` and add them to `lib/`.  In addition, I think that it would make sense to simplify the build path process, either by using relative imports if that's possible (I'm anything but a Java expert so I don't know) or, better yet, through something like Maven that takes care of that stuff for you.  Again, if you agree, pleas let me know; I'd be more than happy to cut a pull request making all these changes myself.

I'm excited to start playing with this code and hope others find my pseudo-documentation here helpful.  Thanks again for sharing your work, and please let me know if you're interested in either/any/all of my pull request proposals, as I'm more than happy to contribute.

**Comment by dangtunguyen** [comment]
Sorry for the late response, Max!
Please go ahead and help me with your PR!

Thank you
Thomas

**Comment by maxvonhippel** [comment]
Excellent, will do, thanks Thomas!  And no worries RE response time, it's totally fine!  I appreciate you sharing your code, it's really interesting :)

**Comment by dangtunguyen** [comment]
You're welcome!

**Comment by maxvonhippel** [comment]
I'm almost done with the PR and am just debugging one last problem, where I get the warning

> The constructor EmptyExpression() is not visible	

In `GListExprTransformer.java` (file is in `/IoTSan/src/edu/ksu/cis/bandera/jjjc/gparser/g2jconverter`), line 205, and one other line with the same error in that file.  I'm sure I can debug this on my own (since I got the code to run previously) but if you happen to know off the top of your head what might be causing the issue I'd appreciate a tip!  Thanks

**Comment by maxvonhippel** [comment]
I am still having the problem RE visibility of `EmptyExpression`, and am not sure how to fix it.  If you have any suggestions I'd appreciate them!  Thanks.

**Comment by maxvonhippel** [comment]
Actually, turns out using Groovy 2.5.1 instead of 3.0.0 solves this.  When you have time I'd suggest changing the project to use 2.5.1.  Unfortunately, although the PR would be trivial, I'm unable to cut it at this time.  Thanks again for sharing your code and all the best!

**Comment by dangtunguyen** [comment]
Thanks, Max. I will do that.
