### ISSUE TITLE
Problem regarding the Java Compilation

### ISSUE THREAD

**Issue by ghost** [dangtunguyen/IoTSan#7]
It is an excellent paper to read. However, I have some difficulties in compiling the Java code. When I used Eclipse 2020-06 (4.16.0), I could not compile it. It gives me this error:

`The type java.lang.StringBuilder cannot be resolved. It is indirectly referenced from required .class files`

When I run it as a Java Application, it gives me this error:

```
java.lang.NoClassDefFoundError: edu/ksu/cis/bandera/bui/AboutBox
Exception in thread "main" 
```

Could you help with me to solve these?

**Comment by ghost** [comment]
Okay, I figured it out. Yesterday I was using soot on Java 9 SDK. However, when I use soot, it shows up some issues regarding java.ext.dir not found. So I googled it. It turns out that soot is not compatible with Java 9. So I switched to Java 8. As it turns out that everything in Java 8 works fine.

**Comment by dangtunguyen** [comment]
Great to hear that!

Best,
Thomas
